-- =============================================================================
-- Business instructions: one long-form, human-authored document per retailer:
-- durable guidance the system must always consider when recommending. See
-- docs/business-instructions.md.
--
-- Visibility: RETAILER-PRIVATE.
--
-- business_instructions_version is APPEND-ONLY. Every save adds the next
-- version; nothing is ever edited in place. The current document is the
-- highest version. Clearing the instructions saves an empty version.
--
--   content       AUTHORITATIVE. The rich-text document (Tiptap/ProseMirror
--                 JSON), validated by the server against the editor's allowed
--                 formatting. Never stored or rendered as raw HTML.
--   content_text  DERIVED. Plain text of the same version, generated by the
--                 server at save time for retrieval. Never edited on its own.
--
-- Authority: only a signed-in owner or admin, in their own session, can save a
-- version; the database records them as its author. The service role, jobs,
-- AI agents and anything else without a user session cannot. Future derived
-- interpretations (structured rules, constraints) must reference the exact
-- (organization_id, version) they came from, are stale once a newer version
-- exists, and can never write back here.
--
-- Concurrency: the next version number is assigned by the database under a
-- per-organization transaction lock. The caller states which version it edited
-- (based_on_version); if another save landed first, the insert fails with
-- 40001 instead of silently superseding it. unique (organization_id, version)
-- is the final backstop.
--
-- Reading: every member reads the CURRENT version; only owners and admins can
-- read earlier versions. For that reason saves are not copied into change_log
-- (which every member can read): this table is its own audit trail.
--
-- The earlier business_rule table (20260927000100) is superseded by this
-- document and left in place, unused.
-- =============================================================================

create table public.business_instructions_version (
  id               uuid primary key default gen_random_uuid(),
  organization_id  uuid not null references public.organization (id) on delete cascade,
  -- Assigned by the database: 1, 2, 3... per organization.
  version          integer not null check (version >= 1),
  -- The version this save was edited from (null for the first). Checked by the
  -- database against the latest version at save time.
  based_on_version integer,
  content          jsonb not null
                   check (jsonb_typeof(content) = 'object' and content ->> 'type' = 'doc'
                          and octet_length(content::text) <= 1000000),
  content_text     text not null check (char_length(content_text) <= 50000),
  -- Set by the database from the acting user, never by the caller.
  created_by       uuid not null,
  created_at       timestamptz not null default now(),
  unique (organization_id, version),
  check (based_on_version is null or based_on_version = version - 1)
);

-- The latest version for an organization, bypassing RLS so policies can use it
-- without recursing into this table's own policy.
create or replace function app.business_instructions_latest_version(p_organization_id uuid)
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select max(v.version)
  from public.business_instructions_version v
  where v.organization_id = p_organization_id
$$;

revoke all on function app.business_instructions_latest_version(uuid) from public;
grant execute on function app.business_instructions_latest_version(uuid) to authenticated, service_role;

-- -----------------------------------------------------------------------------
-- The human-authority boundary and version assignment.
--
-- Deliberately NOT security definer: current_user must be the caller's own
-- role (`authenticated` for a user's session), so the service role and
-- server-side code cannot pass by setting a user id in the request claims.
-- -----------------------------------------------------------------------------
create or replace function app.business_instructions_guard()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  actor  uuid := app.current_user_id();
  latest integer;
begin
  if tg_op = 'DELETE' then
    -- Only a cascade from deleting the whole organization (trigger depth > 1).
    if pg_trigger_depth() > 1 then
      return old;
    end if;
    raise exception 'Business instructions cannot be deleted; save a new version instead'
      using errcode = '42501';
  end if;

  if tg_op = 'UPDATE' then
    raise exception 'Business instructions are append-only; save a new version instead'
      using errcode = '42501';
  end if;

  -- INSERT
  if current_user <> 'authenticated' or actor is null then
    raise exception 'Business instructions can only be changed by a signed-in owner or admin'
      using errcode = '42501';
  end if;
  if not exists (select 1 from app.user_admin_organization_ids() o where o = new.organization_id) then
    raise exception 'Only owners and admins can change business instructions'
      using errcode = '42501';
  end if;

  -- One save at a time per organization, until this transaction ends. The
  -- query below runs after the lock is held, so it sees any save that
  -- committed while this one waited.
  perform pg_advisory_xact_lock(hashtextextended('business_instructions:' || new.organization_id::text, 0));
  latest := app.business_instructions_latest_version(new.organization_id);

  if new.based_on_version is distinct from latest then
    raise exception 'The business instructions changed since you opened them'
      using errcode = '40001';
  end if;

  new.version    := coalesce(latest, 0) + 1;
  new.created_by := actor;
  new.created_at := now();
  return new;
end;
$$;

create trigger business_instructions_guard
  before insert or update or delete on public.business_instructions_version
  for each row execute function app.business_instructions_guard();

create or replace function app.business_instructions_no_truncate()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'Business instructions cannot be truncated' using errcode = '42501';
end;
$$;

create trigger business_instructions_no_truncate
  before truncate on public.business_instructions_version
  for each statement execute function app.business_instructions_no_truncate();

-- -----------------------------------------------------------------------------
-- Row-level security.
--   Members:          the current version only.
--   Owners / admins:  every version; add the next one.
--   Nobody:           update, delete, truncate.
-- -----------------------------------------------------------------------------
alter table public.business_instructions_version enable row level security;

create policy business_instructions_select on public.business_instructions_version
  for select to authenticated
  using (organization_id in (select app.user_admin_organization_ids())
         or (organization_id in (select app.user_organization_ids())
             and version = app.business_instructions_latest_version(organization_id)));

create policy business_instructions_insert on public.business_instructions_version
  for insert to authenticated
  with check (organization_id in (select app.user_admin_organization_ids()));

revoke all on public.business_instructions_version from anon, authenticated;
grant select on public.business_instructions_version to authenticated;
grant insert (organization_id, based_on_version, content, content_text)
  on public.business_instructions_version to authenticated;

-- The current document per organization (RLS of the table applies).
create view public.business_instructions_current
with (security_invoker = true) as
select distinct on (organization_id)
  organization_id, version, content, content_text, created_by, created_at
from public.business_instructions_version
order by organization_id, version desc;

revoke all on public.business_instructions_current from anon, authenticated;
grant select on public.business_instructions_current to authenticated;
